// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using Powerlifing_and_otherML.Model;

namespace Powerlifing_and_otherML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Users\qtckp\OneDrive\Рабочий стол\Powerlift\Estimating RM\MLtests\data.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual RM with predicted RM from sample data...\n\n");
            Console.WriteLine($"MRM: {sampleData.MRM}");
            Console.WriteLine($"Count: {sampleData.Count}");
            Console.WriteLine($"Action: {sampleData.Action}");
            Console.WriteLine($"Sex: {sampleData.Sex}");
            Console.WriteLine($"Age: {sampleData.Age}");
            Console.WriteLine($"Weight: {sampleData.Weight}");
            Console.WriteLine($"Height: {sampleData.Height}");
            Console.WriteLine($"BodyType: {sampleData.BodyType}");
            Console.WriteLine($"CountGroup: {sampleData.CountGroup}");
            Console.WriteLine($"AgeGroup: {sampleData.AgeGroup}");
            Console.WriteLine($"Index: {sampleData.Index}");
            Console.WriteLine($"\n\nActual RM: {sampleData.RM} \nPredicted RM: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
