// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace Powerlifing_and_otherML.Model
{
    public class ModelInput
    {
        [ColumnName("RM"), LoadColumn(0)]
        public float RM { get; set; }


        [ColumnName("MRM"), LoadColumn(1)]
        public float MRM { get; set; }


        [ColumnName("Count"), LoadColumn(2)]
        public float Count { get; set; }


        [ColumnName("Action"), LoadColumn(3)]
        public string Action { get; set; }


        [ColumnName("Sex"), LoadColumn(4)]
        public string Sex { get; set; }


        [ColumnName("Age"), LoadColumn(5)]
        public float Age { get; set; }


        [ColumnName("Weight"), LoadColumn(6)]
        public float Weight { get; set; }


        [ColumnName("Height"), LoadColumn(7)]
        public float Height { get; set; }


        [ColumnName("BodyType"), LoadColumn(8)]
        public string BodyType { get; set; }


        [ColumnName("CountGroup"), LoadColumn(9)]
        public string CountGroup { get; set; }


        [ColumnName("AgeGroup"), LoadColumn(10)]
        public string AgeGroup { get; set; }


        [ColumnName("Index"), LoadColumn(11)]
        public float Index { get; set; }


        [ColumnName("Mult"), LoadColumn(12)]
        public float Mult { get; set; }


    }
}
